name: pray-calendar

services:
  webserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: webserver
      args:
        VITE_BASE: /
        VITE_API_BASE_URL: /api
        VITE_FEATURE_VOLUNTEER_LIST: true
    environment:
      - PORT=8080
      - HOST_BE=http://localhost:8080
      - HOST_FE=http://localhost:5173
      - DB_PATH=./db/data.db
      - ADMIN_NAME=admin
      - ADMIN_PASSWORD=admin
      - RESEND_API_KEY=some-api-key
      - FEATURE_VOLUNTEER_LIST=true
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/db

volumes:
  db-data:
