name: pray-calendar

services:
  webserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: webserver
      args:
        VITE_BASE: /
        VITE_API_BASE_URL: /api
    command: ["--db-path", "./db/data.db", "--admin-name", "admin", "--admin-password", "admin"]
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/db

volumes:
  db-data:
